### ISSUE TITLE
java代码加了base64，php代码应该咋改？

### ISSUE THREAD

**Issue by weisifen** [Tinywan/SM4#1]
java代码：
/**
     * 加密
     *
     * @param data
     * @param key
     * @param charset
     * @return
     * @throws Exception
     */
    public static String sm4Encrypt(String data, String key, String charset) throws Exception {
        byte[] encrypt = SM4Util.encrypt_Ecb_Padding(ByteUtils.fromHexString(key), data.getBytes(charset));
        return Base64.encodeBase64String(encrypt);
    }

    /**
     * 解密
     *
     * @param data
     * @param key
     * @param charset
     * @return
     * @throws Exception
     */
    public static String sm4Decrypt(String data, String key, String charset) throws Exception {
        byte[] encrypt = SM4Util.decrypt_Ecb_Padding(ByteUtils.fromHexString(key), Base64.decodeBase64(data));
        String plainData = new String(encrypt, Charset.forName(charset));
        return plainData;
    }

**Comment by Tinywan** [comment]
使用同样的方式去解码就可以了呀

**Comment by weisifen** [comment]
> 使用同样的方式去解码就可以了呀

大佬，java是直接把byte base64的，php base64_decode之后，会得到乱码。

key:51949f0dd1c3cf5aa948eaa4a786227c
内容：'{"prdCode":"OB00o8u1sfya0oyhdu20210303104855"}'
java（SM4/ECB/PKCS5Padding）加密后的密文：
j7XTRn4HOuMtj27AbFLOn5VkvB/4tvGhmzrukEAzvGw0SBL2g0Hy667jWbkqEBjA


php base64_decode之后就会乱码

烦请大佬再帮忙看看！

**Comment by Tinywan** [comment]
Java 为什么要：byte base64
PHP 解密之后就是一个Json字符串，json_decode($jsonStr, true);

**Comment by weisifen** [comment]
> Java 为什么要：byte base64
> PHP 解密之后就是一个Json字符串，json_decode($jsonStr, true);

这是别人java的SDK，他们做了这样的处理。大佬有时间帮忙看看，php的应该咋改？也可以看下您的邮箱756684177@qq.com，给你发了一些消息

**Comment by Tinywan** [comment]
加密后的字符换应该是小写，你的这个怎么是大写和特殊符号
